.PHONY: clean All

All:
	@echo "----------Building project:[ Challenge02 - Debug ]----------"
	@cd "Challenge02" && "$(MAKE)" -f  "Challenge02.mk"
clean:
	@echo "----------Cleaning project:[ Challenge02 - Debug ]----------"
	@cd "Challenge02" && "$(MAKE)" -f  "Challenge02.mk" clean
