.PHONY: clean All

All:
	@echo "----------Building project:[ Mystring - Debug ]----------"
	@cd "Mystring" && "$(MAKE)" -f  "Mystring.mk"
clean:
	@echo "----------Cleaning project:[ Mystring - Debug ]----------"
	@cd "Mystring" && "$(MAKE)" -f  "Mystring.mk" clean
