.PHONY: clean All

All:
	@echo "----------Building project:[ Assignment01 - Debug ]----------"
	@cd "Assignment01" && "$(MAKE)" -f  "Assignment01.mk"
clean:
	@echo "----------Cleaning project:[ Assignment01 - Debug ]----------"
	@cd "Assignment01" && "$(MAKE)" -f  "Assignment01.mk" clean
